In [5]:
#Numpy는 다차원배열을 처리하는데 필요한 기능을 제공한다
# 수치해석에는 행렬을 사용하는 연산이 중요하기때매 배열에 특화되어있는 Numpy 라이브러리 사용법이 중요하다

from numpy import array
#Numpy라이브러리중 array함수만을 불러오기

# 6.3. 벡터와 행렬 만들기
alist = [0,1,2,3,4]
yvector = array(alist)
avector = array([0,1,2,3,4])
print(yvector)
print(avector)
print(len(avector))

[0 1 2 3 4]
[0 1 2 3 4]
5


In [6]:
amat = array([[0,1,2],[3,4,5],[6,7,8]])
print(amat.shape) #array함수를 사용하여 3x3행렬을 만듦
#.shape는 해당되는 배열의 구조를 알려준다

(3, 3)


In [1]:
# 6.4. arange/linspace함수
# 벡터나 배열을 자동으로 만들어주는 arange/linspace
from numpy import arange
brange = arange(5) #0부터 5-1까지 1씩 증가하는 배열
crange = arange(0,10,3) #0부터 10까지 3씩 증가하는 배열
print(brange) # [0 1 2 3 4]
print(crange) # [0 3 6 9]

[0 1 2 3 4]
[0 3 6 9]


In [2]:
from numpy import linspace
aspace = linspace(0,1,5) #0부터 1까지 등간격(0.25)의 요소 5개 배열
print(aspace)

[0.   0.25 0.5  0.75 1.  ]


In [3]:
# 6.5. ones/zeros/eye 함수
from numpy import ones, zeros, eye
aones = ones((3,3)) # 1로 가득찬 3x3배열 (row, col)
azeros = zeros((3,3)) # 0으로 가득찬 3x3배열 (row, col)
aeye = eye(3) # 대각요소만 1인 3x3배열
print('ones = ',aones)
print('zeros = ',azeros)
print('eye = ',aeye)

ones =  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
zeros =  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
eye =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# 6.6. 행렬 연산 덧셈 뺄셈
from numpy import array
A = array([[1,2,3],[4,5,6],[7,8,9]])
B = array([[-1,1,2],[5,4,2],[3,1,-2]])
madd = A+B
msub = A-B
print(madd)
print(msub)

[[ 0  3  5]
 [ 9  9  8]
 [10  9  7]]
[[ 2  1  1]
 [-1  1  4]
 [ 4  7 11]]


In [7]:
# 행렬에 스칼라수를 곱하거나 나누는 연산
from numpy import array
A = array([[1,2,3],[4,5,6],[7,8,9]])
mult = A * 10.0
divi = A/2.0
print('A*10 = ',mult)
print('A/2 = ',divi)

A*10 =  [[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
A/2 =  [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [9]:
# 6.7. 내적과 행렬곱
# 내적 : 두벡터 성분을 곱하여 합산한 것

# Numpy에서 벡터의 내적은 dot함수가 있음

from numpy import array
a = array([1,2])
b = array([3,4])
dots = a.dot(b) # 벡터 내적
print(dots)

11


In [11]:
from numpy import array, dot

A = array([[1,2,3],[4,5,6],[7,8,9]])
B = array([[-1,1,2],[5,4,2],[3,1,-2]])
mmt = A*B #행렬끼리 곱하면 배열 각 요소별 곱으로 표현됨
dotp = A.dot(B) #dot함수로 찐 행렬곱으로 나타난다
print('행렬곱 = ',mmt)
print('행렬내적 = ',dotp)

행렬곱 =  [[ -1   2   6]
 [ 20  20  12]
 [ 21   8 -18]]
행렬내적 =  [[18 12  0]
 [39 30  6]
 [60 48 12]]


In [12]:
# 6.8. 인덱싱/슬라이싱
# 인덱싱
from numpy import array
a = array([1,2,3,4,5])
print('a[1]=',a[1]) #2
print('a[3]=',a[3]) #4
print('a[-1]=',a[-1]) #뒤에서부터 5

a[1]= 2
a[3]= 4
a[-1]= 5


In [13]:
# 2차원 이상의 배열에서의 인덱싱
from numpy import array
A = array([[1,2,3],[4,5,6],[7,8,9]])
print(A[1,1])#5
print(A[2,1])#8

5
8


In [15]:
# 슬라이싱
from numpy import array
a = array([0,1,2,3,4,5,6,7,8])
print('a[1:5]=',a[1:5]) #[1,2,3,4] 끝자리 -1이다!!!
b = array([0,1,2,3,4,5,6,7,8])
print('a[:3]=',a[:3]) #[0,1,2]

a[1:5]= [1 2 3 4]
a[:3]= [0 1 2]


In [20]:
# 6.9. 벡터화 기법


# 벡터화 기법을 사용하지 않은 예시
from numpy import linspace, zeros, cos
x = linspace(0,2,10) # 0~2까지 등간 10개
n = len(x) #10
y = zeros(n) #10개의 0이 들어있는 벡터/코사인함수 결과값을 저장할 빈 벡터 선언
print(y)

for i in range(n): #10번 수행
    y[i] = cos(x[i]) #각각의 x값을 cos함수에 넣은것임
    print('%8.4f '%y[i])


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  1.0000 
  0.9754 
  0.9028 
  0.7859 
  0.6303 
  0.4437 
  0.2352 
  0.0152 
 -0.2055 
 -0.4161 
0.9754100853894475


In [21]:
# 벡터화 기법을 사용한 예시
from numpy import linspace, zeros, cos
x = linspace(0,2,10)
y = cos(x)
print(y)

[ 1.          0.97541009  0.90284967  0.78588726  0.63027505  0.44366602
  0.23523757  0.01524018 -0.20550672 -0.41614684]


In [ ]:
# 요약
# 1. Numpy 라이브러리를 사용해서 벡터나 행렬을 만들 때에는
#     from numpy import array 와 같이 선언하여 array함수를 사용한다
# 2. 요소의 수가 정해진 배열을 자동으로 만들고 싶을 때는 linspace
#     x = linspace(-1,1,10) -1~1사이의 10개 요소가 등간으로 들어감
# 3. 내적은 dot함수/ 행렬곱은 A*B => 둘이 결과물이 다르므로 주의
# 4. 인덱싱, 슬라이싱 가능